# Task 1

## _Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”​ 3​, 45​, 83​, 21​_

## _Have a go at ‘w’ ‘r’  ‘a’_

In [53]:
numbers_file = open("my_numbers_file.txt", 'w')

numbers_file.write(str("3,45,83,21"))

numbers_file.close()

In [54]:
with open("my_numbers_file.txt", "r") as numbers_file:
    info = numbers_file.read()
    print(info)

numbers_file.close()

3,45,83,21


In [55]:
numbers_file = open("my_numbers_file.txt", 'a')
numbers_file.write("More numbers: 900,1,4,6")
numbers_file.close()

In [56]:
with open("my_numbers_file.txt", "r") as numbers_file:
    info = numbers_file.read()
    print(info)

numbers_file.close()

3,45,83,21More numbers: 900,1,4,6


# Task 2 

## _Write a program to ask a student for their percentage mark and convert this to a grade.​ The conversion will be done in a function called mark_grade_.

In [47]:
def mark_grade(grade):
    if grade <= 45:
        print('Your grade is D')
    elif grade >= 45 and grade <=55:
        print('Your grade is C')
    elif grade >= 55 and grade <= 70:
        print('Your grade is B')
    elif grade >= 70 and grade <=100:
        print('Your grade is A')

    return grade
    
def tar_grade(target_grade):    
    if target_grade > grade:
        print('Your target grade is higher than your actual grade')
    elif target_grade == grade:
        print('Your target grade is equal to your grade')
    elif target_grade < grade:
        print('Your target grade is lower than your actual grade')

    return target_grade

In [48]:
grade = int(input('Enter your precentage mark here to find out your grade:'))
target_grade = int(input('Enter your target grade here:'))

In [49]:
mark_grade(grade)

tar_grade(target_grade)


Your grade is B
Your target grade is lower than your actual grade


40

In [2]:
import numpy as np

# Task 3

## _Create a 1D array of numbers from 0 to 9_

In [76]:
one_dim_array = np.arange(0,10)

print(one_dim_array)

[0 1 2 3 4 5 6 7 8 9]


# Task 4

## _Create a 3×3 NumPy array of all Boolean value Trues_


In [101]:
bool_array = np.array([1,1,1,1,1,1,1,1,1], dtype = bool)

print(len(bool_array))

print(bool_array)

9
[ True  True  True  True  True  True  True  True  True]


In [102]:
new_bool_array = bool_array.reshape(3,3)

print(new_bool_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# Task 5

## _Extract all odd numbers from array of 1-10_

In [109]:
odd_numbers_array = np.arange(1,11,2)

print(odd_numbers_array)

[1 3 5 7 9]


# Task 6

## _Replace all odd numbers in an array of 1-10 with the value -1​_

In [110]:
odd_numbers_array[odd_numbers_array % 2 != 0] = -1

print(odd_numbers_array)

[-1 -1 -1 -1 -1]


# Task 7

## _Convert a 1D array to a 2D array with 2 rows_

In [124]:
one_d_array = np.arange(1,5)

new_twod_array = one_d_array.reshape(2,2)

print(new_twod_array)

[[1 2]
 [3 4]]


# Task 8

## _Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals_

In [134]:
a_array = np.arange(1,5)

b_array = np.arange(6,10)

vertical_array = np.vstack((b_array,a_array))

print(vertical_array)

multi = np.dot(a_array,b_array)

print(multi)

sum_of_arrays = np.sum(vertical_array)

print(sum_of_arrays)



[[6 7 8 9]
 [1 2 3 4]]
80
40


# Task 9 

## _Create the following pattern without hardcoding. Use only NumPy  functions. array(1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3)​_


In [148]:
first = np.ones(3)

second = np.ones(3) * 2

third = np.ones(3) * 3

fourth = np.arange(1,4)

fifth = fourth.copy()

sixth = fifth.copy()

pattern = np.concatenate((first,second,third,fourth,fifth,sixth))

print(pattern)


[1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]


# Task 10

## _In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating  items present in array b​_

In [138]:
aarray = np.array([1,2,3,4,5])

barray = np.array([4,5,6,7,8,9])

joined = np.concatenate((aarray,barray))

print(joined)

unique_array = np.unique(joined)

print(unique_array)

[1 2 3 4 5 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


# Task 11

## _Get all items between 3 and 7 from a and b and sum them together_

In [149]:
required_items = unique_array[2:8]

total = np.sum(required_items)

print(total)

33
